### ISSUE TITLE
Bug: Help page returns Internal Server Error

### ISSUE THREAD

**Issue by KatiRG** [ongov/ckanext-ontario_theme#206]
Argument `{'package_type': 'dataset'}` is passed to `dispatch_request()` in `lib/python3.8/site-packages/flask/app.py` when clicking on the Help menu item. No arguments should be passed.

```
ERROR [ckan.config.middleware.flask_app] help() got an unexpected keyword argument 'package_type'
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1955, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1941, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: help() got an unexpected keyword argument 'package_type'
```

**Comment by KatiRG** [comment]
Not reproducible.
