### ISSUE TITLE
Sqlalchemy throws error that role does not exist on Azure database

### ISSUE THREAD

**Issue by KatiRG** [ongov/ckanext-ontario_theme#225]
## Problem
Trying to launch ckan 2.9/python 3.8 on Azure VM, with database `datastore` on a separate postgres server, but sqlalchemy complains that the role for the `read_url` user defined in `ckan.ini` does not exist.

The database access for the roles is defined in `ckan.ini` as:
```
sqlalchemy.url = postgresql://ckan_default@<domain>:<passwd>@<domain>.postgres.database.azure.com:<port>/<dbname>?sslmode=require

ckan.datastore.write_url = postgresql://ckan_default@<domain>:<passwd>@<domain>.postgres.database.azure.com:<port>/datastore?sslmode=require

ckan.datastore.read_url = postgresql://datastore_default@<domain>:<passwd>@<domain>.postgres.database.azure.com:<port>/datastore?sslmode=require

```

## Relevant info
- This issue has been reported previously and is still open: https://github.com/ckan/ckan/issues/6308.
- [This group](https://github.com/geosolutions-it/C195-azure-workspace/issues/27) suggests the problem can be avoided by defining the read_url user with the `@<domain>` explicitly: `psql -U $arg1@$arg3 -h $arg4 postgres -c "CREATE ROLE "datastore_ro@$arg3" NOCREATEDB NOCREATEROLE LOGIN PASSWORD '${arg5}';"`
- The read_url user can successfully log into the postgres database on the command line with the credentials as defined in `ckan.ini`.
- In [postgres.py](https://github.com/ckan/ckan/blob/master/ckanext/datastore/backend/postgres.py#L1797), removing the `@<domain>` from `read_connection_user` allows the ckan run command to complete without throwing any errors

Full stack trace:

```
$ ckan -c /etc/ckan/default/ckan.ini run
2022-07-08 21:10:15,238 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2022-07-08 21:10:15,238 INFO  [ckan.config.environment] Loading static files from public
2022-07-08 21:10:15,274 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
2022-07-08 21:10:15,965 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: role "datastore_default@<domain>" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 33, in <module>
    sys.exit(load_entry_point('ckan', 'console_scripts', 'ckan')())
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 115, in parse_args
    result = super(ExtendableGroup, self).parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 125, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 134, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 56, in __init__
    self.app = make_app(self.config)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 123, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 165, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 193, in load
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 153, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 309, in update_config
    plugin.configure(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/plugin.py", line 82, in configure
    self.backend.configure(config)
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1780, in configure
    self._check_urls_and_permissions()
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1664, in _check_urls_and_permissions
    if not self._read_connection_has_correct_privileges():
  File "/usr/lib/ckan/default/src/ckan/ckanext/datastore/backend/postgres.py", line 1709, in _read_connection_has_correct_privileges
    have_privilege = write_connection.execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1149, in _execute_text
    ret = self._execute_context(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) role "datastore_default@<domain>" does not exist

[SQL: SELECT has_table_privilege(%s, '_foo', %s)]
[parameters: ('datastore_default@<domain>', 'INSERT')]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by KatiRG** [comment]
Closing issue. On flexible Postgres v14 servers, there is no longer any issue and no special hack is needed in `postgres.py`.
